# Generated by Django 5.1.3 on 2024-11-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('nicname', models.CharField(max_length=50)),
                ('gender', models.CharField(default='Man', max_length=10)),
            ],
        ),
    ]
